### ISSUE TITLE
酷安分享

### ISSUE THREAD

**Issue by yi-Xu-0100** [ysy950803/FiveGSwitcher#1]
非常感谢作者的文章和开源~👍

我在酷安看到的，但是没看到链接指向这里，所以我再次分享了这个项目到酷安，以感谢这个开源力作！❤️

但是个人是酷安新手，没法插入直链到文章中。 😰

[个人发布的酷安分享文章](https://www.coolapk.com/feed/26484262?shareKey=NjZmY2RiYmFhYmM4NjA4MTA5MmU~&shareUid=2372196&shareFrom=com.coolapk.market_11.1.2)

该 issue 不涉及 bug 反馈，会直接关闭掉的。😊

**Comment by yi-Xu-0100** [comment]
我制作了蓝奏云的分享版，方便下载。说明中有指向该仓库。

链接: https://wwa.lanzous.com/b016d747e
密码: 2jsy

**Comment by ysy950803** [comment]
@yi-Xu-0100 谢谢你的分享！
