### ISSUE TITLE
如何用Shell触发5G开关

### ISSUE THREAD

**Issue by yu-liang-zheng** [ysy950803/FiveGSwitcher#2]
想实现，每天晚上十二点，定时关掉5g。

直接用 am start -n com.ysy.fivegswitcher/.MainActivity，会弹窗“选择运营商/选择网络设置”。

请问一下，有没有办法用shell触发该应用，实习5g网络的开关，谢谢了😃

**Comment by ysy950803** [comment]
@yu-liang-zheng 嗯，目前以你的方式应该还不能实现，因为MainActivity是打开网络设置，5G开关本身是一个TileService快捷方式。
如果你只是想定时关闭网络的话，MIUI的手机管家有一个自动任务的功能，可以定时关闭数据开关或者开启飞行模式。
如果你确实需要定时开关5G，我可以试试给你弄个单独的Activity或者Service来方便调用。

**Comment by ysy950803** [comment]
@yu-liang-zheng 可以下载最新版试试。参数在README。

**Comment by yu-liang-zheng** [comment]
感谢支持。
在MIUI 12的k30pro上，能正常调用。
