### ISSUE TITLE
建议去掉label中“开关”二字，改为“5G”

### ISSUE THREAD

**Issue by ysc3839** [ysy950803/FiveGSwitcher#4]
感觉怪怪的，毕竟系统中其他开关也不会写成“静音开关”、“热点开关”。
https://github.com/ysy950803/FiveGSwitcher/blob/8863790aad076239ed88ca624c46c4ffd085a503/app/src/main/res/values-zh-rCN/strings.xml#L4

**Comment by ysy950803** [comment]
好建议，不过当时设计这个时，是按照早期的系统自带的“4G开关”来命名的。后面考虑修改一下。
